<?php

/**
 * Implements hook_layout_alter().
 */
function multiple_definition_files_layout_alter(&$definitions) {
  \Drupal::service('multiple_definition_files.layout_discovery')->addThemeLayouts($definitions);
}

/**
 * Implements hook_library_info_alter().
 */
function multiple_definition_files_library_info_alter(&$libraries, $extension) {
  \Drupal::service('multiple_definition_files.library_discovery')->addThemeLibraries($libraries, $extension);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function multiple_definition_files_preprocess_layout(&$variables) {
  // Copy each region variable to root, but only if a root variable with that
  // name does not already exist.
  /** @var \Drupal\Core\Layout\LayoutDefinition $layout */
  $layout = $variables['layout'];
  foreach ($layout->getRegionNames() as $name) {
    if (!isset($variables[$name]) && isset($variables['content'][$name])) {
      $variables[$name] = $variables['content'][$name];
    }
  }
}
